// <auto-generated/>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Azure.Functions.Worker.Context.Features;
using Microsoft.Azure.Functions.Worker.Invocation;
using Microsoft.Extensions.Logging;
using Net8AOTApp;

namespace Microsoft.Azure.Functions.Worker
{
    internal class DirectFunctionExecutor : IFunctionExecutor
    {
        private readonly IFunctionActivator _functionActivator;
        private readonly Dictionary<string, Type> types = new()
        {
            { "Net8AOTApp.Function1", Type.GetType("Net8AOTApp.Function1")! },
        };

        public DirectFunctionExecutor(IFunctionActivator functionActivator)
        {
            _functionActivator = functionActivator ?? throw new ArgumentNullException(nameof(functionActivator));
        }

        public async ValueTask ExecuteAsync(FunctionContext context)
        {
            var inputBindingFeature = context.Features.Get<IFunctionInputBindingFeature>()!;
            var inputBindingResult = await inputBindingFeature.BindFunctionInputAsync(context)!;
            var inputArguments = inputBindingResult.Values;

            if (string.Equals(context.FunctionDefinition.EntryPoint, "Net8AOTApp.Function1.Run", StringComparison.OrdinalIgnoreCase))
            {
                var instanceType = types["Net8AOTApp.Function1"];
                //var i2 = _functionActivator.CreateInstance(instanceType, context) as Net8AOTApp.Function1;
                var ilogger = context.InstanceServices.GetService<ILogger<Function1>>();
                var i = new Net8AOTApp.Function1(ilogger);
                context.GetInvocationResult().Value = i.Run((Microsoft.Azure.Functions.Worker.Http.HttpRequestData)inputArguments[0]);
            }
        }
    }
    public static class FunctionExecutorHostBuilderExtensions
    {
        ///<summary>
        /// Configures an optimized function executor to the invocation pipeline.
        ///</summary>
        public static IHostBuilder ConfigureGeneratedFunctionExecutor(this IHostBuilder builder)
        {
            return builder.ConfigureServices(s =>
            {
                s.AddSingleton<IFunctionExecutor, DirectFunctionExecutor>();
            });
        }
    }
}
